# Generated by Django 5.1.1 on 2024-09-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='iphone',
            name='smart_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iphone.smartshop'),
        ),
    ]
